### ISSUE TITLE
Manifest version 2 is deprecated...

### ISSUE THREAD

**Issue by rmonroe041** [nagornyi/ukrainian-phonetic-keyboard-chromeos#1]
From the phonetic Ukrainian keyboard program, Line 19. "manifest_version": 2, I get the following error message within the Extensions Developer Mode: "Manifest version 2 is deprecated and will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
Every time I install this Phonetic Ukrainian keyboard extension, it gets DELETED from my Chromebook!

(here's what's on that mv2 transition page:)
As we look to the future by continuing to iterate on and improve upon Manifest V3 functionality, we also want to share details about the plan to phase out Manifest V2 extensions.
There are two key dates for the phase-out:

January 17, 2022: New Manifest V2 extensions will no longer be accepted by the Chrome Web Store. Developers may still push updates to existing Manifest V2 extensions, but no new Manifest V2 items may be submitted.

January 2023: The Chrome browser will no longer run Manifest V2 extensions. Developers may no longer push updates to existing Manifest V2 extensions.

**Comment by nagornyi** [comment]
I've updated the manifest, it should be working now. Also make sure you store the folder with the manifest file on your main Chromebook drive, not on a portable flash drive.
